name: Build CampusCoffee

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Java version
        run: java --version
      - uses: jdx/mise-action@v2

      - name: Install correct versions (optional override)
        run: mise install
      - name: Setup JAVA_HOME
        run: echo "JAVA_HOME=$HOME/.local/share/mise/candidates/java/current" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn -B package --file pom.xml
