name: Build CampusCoffee

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - name: Install correct versions (optional override)
        run: mise install

      - name: Build with Maven
        run: mvn -B package --file pom.xml
